# Hipótese 5: O Tempo de Normalização das Portas E as Manutenções Corretivas Realizadas Tem Correlação?

## 1. Contexto e Fundamentação Teórica
As Portas de Plataforma (PSDs) são equipamentos eletromecânicos submetidos a ciclos contínuos de abertura e fechamento (ciclagens) para permitir o embarque e desembarque seguro de passageiros nas estações.

A hipótese operacional central estabelece que o tempo que ela demore para ser normalizadas são as que precisam ser consertadas ou dando problemas mais para frente. Isso nos trará dois dados importantes: tempos pequenos de normalização são exclusivamente portas que tiveram apenas obstrução e caso o tempo de normalização passe de X horas, deve ser consertada. 

---

## 2. Definindo a Questão Investigada
* **Portas e seu tempo de normalização**: O tempo para normalizar/fechar é um tempo em que a porta demora para voltar para seu funcionamento normal, mas há tempos bem grandes (chegando à quase 12h). A ideia é comprarar todas as portas que tiveram o tempo de normalização com os problemas, fazendo uma só planilha e ver se o tempo está relacionado à algum problema ou algo do tipo.

---

## 3. Metodologia de Análise
Para testar a validade da hipótese, os dados brutos de alarmes do sistema de PSDs são processados seguindo as seguintes etapas:
1. Normalização e fazer as planilhas se conversarem

In [23]:
from pathlib import Path
import pandas as pd
import openpyxl

correcao_emergencial = pd.read_excel(
    "../../data/Ordens do SAP - Corretiva emergencial (ZM01).XLSX"
)

correcao_programada = pd.read_excel(
    "../../data/Ordens do SAP -Corretiva programada (ZM02).XLSX"
)

alarmes = pd.read_excel(
    "../../data/Alarmes do sistema de PSD.xlsx"
)

print("Emergencial:", correcao_emergencial.shape)
print("Programada:", correcao_programada.shape)
print("Alarmes:", alarmes.shape)

Emergencial: (10647, 28)
Programada: (1163, 28)
Alarmes: (150003, 7)

In [24]:
display(correcao_emergencial.head())
display(correcao_programada.head())
display(alarmes.head())

,Tipo de Nota,Nota,Ordem,Indisponível,Falha,IQM,Analisada,Comentários Classificação Engenharia,Perfil do catálogo,Descrição,...,Centro de Trabalho Responsável,Sintoma,Objeto,Defeito,Causa,Ação,Data Análise,Hora Análise,Encerram.por Data,Hora de Encerramento
0,Z1,14943931,53954586.0,X,X,NaN,NaN,MI/ NVT1 - AVARIADA,6PSD,PSD PL 01-02 Sem status para o CCO,...,SP04IBUT,LAÇO DE PDM ABERTO,NaN,NaN,NaN,NaN,2025-12-05,17:50:50,NaT,00:00:00
1,Z1,15133619,54145839.0,NaN,NaN,NaN,X,DU,6PSD,PSD - PDM's não abriram PLT02,...,SP04IBUT,TODAS AS PDM DA FACHADA NÃO ABREM,CABEAMENTO,CONTROLADOR PCC COMUNICACAO,ERRO DE COMUNICAÇÃO,RESETADO E TESTADO,2026-03-03,17:48:50,2026-02-27,14:26:36
2,Z1,13894133,52913343.0,NaN,NaN,NaN,X,CF/FALHA COMUNICAÇÃO,6PSD,PSD server s/ status das plataformas,...,SP04IBUT,PSD SERVER COM INDICAÇÃO DE FALHA NA PLA,RACK WCN,SENSOR DESTRAVADO AVARIADO,DESGASTE,RESETADO E TESTADO,NaT,00:00:00,2024-04-18,07:33:25
3,Z1,14713349,53724958.0,X,NaN,NaN,X,NC/ RESET,6PSD,BUT PLT 1 PORTAS NAO ABRIRAM,...,SP04IBUT,TODAS AS PDM DA FACHADA NÃO ABREM,CABO/CONECTORES,SWITCH TRAVADO,DESGASTE,RESETADO E TESTADO,2025-08-14,16:38:16,2025-07-08,04:40:58
4,Z1,14643768,53655728.0,X,NaN,NaN,X,NC/RESET,6PSD,PSD plt 1 - Falha geral de abertura,...,SP04IBUT,PDM NÃO ABRE,CABEAMENTO,BAIXA ISOLACAO,FALHA CBTC,RESETADO E TESTADO,2025-05-29,10:58:06,2025-05-28,14:37:13

,Tipo de Nota,Nota,Ordem,Indisponível,Falha,IQM,Analisada,Comentários Classificação Engenharia,Perfil do catálogo,Descrição,...,Centro de Trabalho Responsável,Sintoma,Objeto,Defeito,Causa,Ação,Data Análise,Hora Análise,Encerram.por Data,Hora de Encerramento
0,Z2,15069252,54081268.0,NaN,NaN,NaN,NaN,NaN,6PSD,Porta PCC-PSD a,...,SP04IBUT,PDM NÃO ABRE,"ESTRUTURA, ACABAMENTO, E ACESSÓRIOS DO P",PORTA DESAJUSTADA,FALTA FIXACAO,FIXADO,NaT,00:00:00,2026-01-25,16:50:18
1,Z2,14647619,53659484.0,NaN,NaN,NaN,NaN,NaN,6PSD,PDMs plat 1 e 2 com falha momentânea.,...,SP04IBUT,MAU CONTATO,SWITCK DE COMUNICAÇÃO,SEM CONEXAO ELETRICA,ERRO DE SOFTWARE,RESETADO E TESTADO,NaT,00:00:00,2025-06-01,04:36:44
2,Z2,14682623,53694340.0,NaN,NaN,NaN,NaN,NaN,6PSD,Rele painel SSE intermitente,...,SP04IBUT,FACHADA PSD SEM ALIMENTAÇÃO,DISPOSITIVO DE PROTECAO,CONVERSOR DE TENSAO AVARIADO,OPERACAO INDEVIDA,SUBSTITUIDO(A),NaT,00:00:00,2025-06-19,05:10:12
3,Z2,14864269,53874165.0,NaN,NaN,NaN,NaN,NaN,6PSD,Multimedidor SSE moldura solta,...,SP04IBUT,ESTRUTURA DANIFICADA,MULTIMEDIDOR,VIDRO QUEBRADO,DESGASTE,SUBSTITUIDO(A),NaT,00:00:00,2025-09-30,14:53:22
4,Z2,13390549,52423535.0,NaN,NaN,NaN,NaN,NaN,6PSD,Volume do P.A baixo.,...,SP04IBUT,SERVIDOR SEM COMUNICACAO,SWITCK DE COMUNICAÇÃO,BAIXA ISOLACAO,FALTA FIXACAO,APERTADO(A),NaT,00:00:00,2023-07-27,13:52:02

,TAG,Horário do Alarme,Estação,Porta,Alarme,Horário da Normalizacao,Tempo de Normalização
0,PSD_FAL_FAL2_PDM09_OBS,2026-05-12 08:16:52.657,FAL,9.0,OBS,2026-05-12 08:16:53.670,"0 dias, 00:00:01"
1,PSD_LUZ_LUZ1_PDM08_OBS,2026-05-12 08:15:09.913,LUZ,8.0,OBS,2026-05-12 08:15:10.917,"0 dias, 00:00:01"
2,PSD_FAL_FAL1_PDM15_OBS,2026-05-12 08:14:06.657,FAL,15.0,OBS,2026-05-12 08:14:07.670,"0 dias, 00:00:01"
3,PSD_LUZ_LUZ1_PDM19_OBS,2026-05-12 08:09:31.930,LUZ,19.0,OBS,2026-05-12 08:09:32.917,"0 dias, 00:00:01"
4,PSD_FRE_FRE1_PDM14_OBS,2026-05-12 08:05:05.830,FRE,14.0,OBS,2026-05-12 08:05:14.847,"0 dias, 00:00:09"

In [25]:
correcao_emergencial = correcao_emergencial[
    ["Local de Instalação", "Início avaria", "Hora início avaria", "Fim da avaria", "Hora do fim da avaria", "Sintoma", "Objeto", "Defeito", "Causa"]
]

correcao_programada = correcao_programada[
    ["Local de Instalação", "Início avaria", "Hora início avaria", "Fim da avaria", "Hora do fim da avaria", "Sintoma", "Objeto", "Defeito", "Causa"]
]

display(correcao_emergencial.head())
display(correcao_programada.head())
display(alarmes.head())

,Local de Instalação,Início avaria,Hora início avaria,Fim da avaria,Hora do fim da avaria,Sintoma,Objeto,Defeito,Causa
0,SP04-6-PSD-BUT,14/11/2025,06:35:28,NaN,00:00:00,LAÇO DE PDM ABERTO,NaN,NaN,NaN
1,SP04-6-PSD-BUT,27/02/2026,07:33:00,27/02/2026,12:00:00,TODAS AS PDM DA FACHADA NÃO ABREM,CABEAMENTO,CONTROLADOR PCC COMUNICACAO,ERRO DE COMUNICAÇÃO
2,SP04-6-PSD-BUT-P1S1,18/04/2024,06:00:00,18/04/2024,07:30:00,PSD SERVER COM INDICAÇÃO DE FALHA NA PLA,RACK WCN,SENSOR DESTRAVADO AVARIADO,DESGASTE
3,SP04-6-PSD-BUT-P1S1,07/07/2025,18:38:00,08/07/2025,03:00:00,TODAS AS PDM DA FACHADA NÃO ABREM,CABO/CONECTORES,SWITCH TRAVADO,DESGASTE
4,SP04-6-PSD-BUT-P1S1-PSSE1,28/05/2025,09:10:00,28/05/2025,10:00:00,PDM NÃO ABRE,CABEAMENTO,BAIXA ISOLACAO,FALHA CBTC

,Local de Instalação,Início avaria,Hora início avaria,Fim da avaria,Hora do fim da avaria,Sintoma,Objeto,Defeito,Causa
0,SP04-6-PSD-BUT,25/01/2026,08:20:00,25/01/2026,09:30:00,PDM NÃO ABRE,"ESTRUTURA, ACABAMENTO, E ACESSÓRIOS DO P",PORTA DESAJUSTADA,FALTA FIXACAO
1,SP04-6-PSD-BUT-P1S1,30/05/2025,09:30:00,01/06/2025,04:00:00,MAU CONTATO,SWITCK DE COMUNICAÇÃO,SEM CONEXAO ELETRICA,ERRO DE SOFTWARE
2,SP04-6-PSD-BUT-P2S1-PSSE2,19/06/2025,02:00:00,19/06/2025,04:30:00,FACHADA PSD SEM ALIMENTAÇÃO,DISPOSITIVO DE PROTECAO,CONVERSOR DE TENSAO AVARIADO,OPERACAO INDEVIDA
3,SP04-6-PSD-BUT-P2S1-PSSE2,30/09/2025,09:00:00,30/09/2025,12:00:00,ESTRUTURA DANIFICADA,MULTIMEDIDOR,VIDRO QUEBRADO,DESGASTE
4,SP04-6-PSD-BUT-PLT1,21/07/2023,14:00:00,27/07/2023,13:50:56,SERVIDOR SEM COMUNICACAO,SWITCK DE COMUNICAÇÃO,BAIXA ISOLACAO,FALTA FIXACAO

,TAG,Horário do Alarme,Estação,Porta,Alarme,Horário da Normalizacao,Tempo de Normalização
0,PSD_FAL_FAL2_PDM09_OBS,2026-05-12 08:16:52.657,FAL,9.0,OBS,2026-05-12 08:16:53.670,"0 dias, 00:00:01"
1,PSD_LUZ_LUZ1_PDM08_OBS,2026-05-12 08:15:09.913,LUZ,8.0,OBS,2026-05-12 08:15:10.917,"0 dias, 00:00:01"
2,PSD_FAL_FAL1_PDM15_OBS,2026-05-12 08:14:06.657,FAL,15.0,OBS,2026-05-12 08:14:07.670,"0 dias, 00:00:01"
3,PSD_LUZ_LUZ1_PDM19_OBS,2026-05-12 08:09:31.930,LUZ,19.0,OBS,2026-05-12 08:09:32.917,"0 dias, 00:00:01"
4,PSD_FRE_FRE1_PDM14_OBS,2026-05-12 08:05:05.830,FRE,14.0,OBS,2026-05-12 08:05:14.847,"0 dias, 00:00:09"

In [26]:
print("Alarmes:")
print(alarmes.isnull().sum())

print("\nCorretiva emergencial:")
print(correcao_emergencial.isnull().sum())

print("\nCorretiva programada:")
print(correcao_programada.isnull().sum())

Alarmes:
TAG                            1
Horário do Alarme          37252
Estação                        3
Porta                          3
Alarme                         3
Horário da Normalizacao        3
Tempo de Normalização          3
dtype: int64

Corretiva emergencial:
Local de Instalação         0
Início avaria               0
Hora início avaria          0
Fim da avaria             326
Hora do fim da avaria       0
Sintoma                     0
Objeto                    982
Defeito                   986
Causa                    1045
dtype: int64

Corretiva programada:
Local de Instalação       0
Início avaria             0
Hora início avaria        0
Fim da avaria            39
Hora do fim da avaria     0
Sintoma                   0
Objeto                   39
Defeito                  39
Causa                    42
dtype: int64

In [27]:
import numpy as np
alarmes_trat = alarmes.copy()

# Estação
alarmes_trat["estacao_key"] = (
    alarmes_trat["Estação"]
    .astype("string")
    .str.strip()
    .str.upper()
)

# Porta
alarmes_trat["porta_key"] = pd.to_numeric(
    alarmes_trat["Porta"],
    errors="coerce"
).astype("Int64")

# Extrair plataforma da TAG
# Exemplo: PSD_FAL_FAL2_PDM09_OBS
plataforma = alarmes_trat["TAG"].astype(str).str.extract(
    r"(?:^|_)([A-Z]{3})([12])_PDM(\d{2})(?:_|$)"
)

alarmes_trat["plataforma_key"] = pd.to_numeric(
    plataforma[1],
    errors="coerce"
).astype("Int64")

In [28]:
alarmes_trat["inicio_alarme"] = pd.to_datetime(
    alarmes_trat["Horário do Alarme"],
    errors="coerce"
)

alarmes_trat["fim_alarme"] = pd.to_datetime(
    alarmes_trat["Horário da Normalizacao"],
    errors="coerce"
)

In [29]:
alarmes_trat["tempo_normalizacao"] = (
    alarmes_trat["fim_alarme"]
    - alarmes_trat["inicio_alarme"]
)

alarmes_trat["tempo_normalizacao_min"] = (
    alarmes_trat["tempo_normalizacao"]
    .dt.total_seconds() / 60
)

In [30]:
display(
    alarmes_trat[
        [
            "TAG",
            "estacao_key",
            "plataforma_key",
            "porta_key",
            "inicio_alarme",
            "fim_alarme",
            "tempo_normalizacao_min"
        ]
    ].head(10)
)

,TAG,estacao_key,plataforma_key,porta_key,inicio_alarme,fim_alarme,tempo_normalizacao_min
0,PSD_FAL_FAL2_PDM09_OBS,FAL,2,9,2026-05-12 08:16:52.657,2026-05-12 08:16:53.670,0.016883
1,PSD_LUZ_LUZ1_PDM08_OBS,LUZ,1,8,2026-05-12 08:15:09.913,2026-05-12 08:15:10.917,0.016733
2,PSD_FAL_FAL1_PDM15_OBS,FAL,1,15,2026-05-12 08:14:06.657,2026-05-12 08:14:07.670,0.016883
3,PSD_LUZ_LUZ1_PDM19_OBS,LUZ,1,19,2026-05-12 08:09:31.930,2026-05-12 08:09:32.917,0.016450
4,PSD_FRE_FRE1_PDM14_OBS,FRE,1,14,2026-05-12 08:05:05.830,2026-05-12 08:05:14.847,0.150283
5,PSD_FRE_FRE1_PDM14_OBS,FRE,1,14,2026-05-12 08:05:02.847,2026-05-12 08:05:03.847,0.016667
6,PSD_LUZ_LUZ1_PDM15_OBS,LUZ,1,15,2026-05-12 07:52:33.930,2026-05-12 07:52:34.930,0.016667
7,PSD_HIG_HIG1_PDM16_OBS,HIG,1,16,2026-05-12 07:52:23.820,2026-05-12 07:52:24.820,0.016667
8,PSD_FAL_FAL1_PDM14_OBS,FAL,1,14,2026-05-12 07:50:21.703,2026-05-12 07:50:22.670,0.016117
9,PSD_LUZ_LUZ1_PDM08_OBS,LUZ,1,8,2026-05-12 07:33:46.900,2026-05-12 07:33:47.900,0.016667